version: '3'
services:
  app:
    build:
      context: ./
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    ports:
      - "8089:80"
    #environment:
    #  - .env
networks:
  default:
    name: captain-overlay-network
    external: true
    #extra_hosts:
    #  - "host.docker.internal:host-gateway
